# Generated by Django 5.1.2 on 2024-10-24 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Telefono', models.IntegerField(unique=True)),
                ('Fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_entrada', models.DateField()),
                ('Fecha_salida', models.DateField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Forma_de_pago', models.CharField(max_length=100)),
                ('Monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reserva', unique=True)),
            ],
        ),
    ]
